builders:
  config_builder:
    import: "package:material_symbols_icons/src/varied_icons_generator.dart"
    builder_factories: ["variedIconsBuilder"]
    auto_apply: root_package
    build_to: source
    build_extensions: { ".dart": [".varied.dart"] }
